# Generated by Django 6.0.2 on 2026-02-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(help_text='Введите фамилию автора', max_length=100, verbose_name='Фамилия автора'),
            preserve_default=False,
        ),
    ]
