# Generated by Django 6.0.2 on 2026-02-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookinstance_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='postup_date',
            field=models.DateField(help_text='Дата поступления', null=True),
        ),
    ]
