# Generated by Django 6.0.2 on 2026-02-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_bookinstance_postup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='postup_date',
            field=models.DateField(blank=True, help_text='Дата поступления', null=True, verbose_name='Выберите дату поступления экземпляра книги'),
        ),
    ]
