# Generated by Django 6.0.2 on 2026-02-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_bookinstance_postup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='Выберите автора книги', related_name='books', to='catalog.author', verbose_name='Автор книги'),
        ),
    ]
